### ISSUE TITLE
Consider GraphQL instead of Rest as API endpoint

### ISSUE THREAD

**Issue by tobiasdiez** [ourresearch/openalex-api#1]
Given the highly complex and inter-connected structure of citation data, I would recommend to choose GraphQL instead of Rest. For example, if one wants to know the average impact factor of all publications of a certain author (not that this is a good metric; its merely an example), then one would need to first fetch all publications of the author, and then for each publication the journal with its impact factor. Naively counting this leads to `1 + # publications * # journals` requests to the api, with a lot of unnecessary information transferred (for example, we don't care about the abstracts of each publication, but it may be included in the api response).

With GraphQL, this could be achieved using a simple query along the lines:
```graphql
query author(name: '...') {
   publications {
       journal {
         impactFactor
      }
   }
}
``` 
Which is one request, and returns exactly the data we need.

The above is of course only one example. In my experience, the graph-like structure of the citation data with its main players of authors, publications, journals and institutions leads to a lot of over- and under-fetching. This is exactly the types of problems which graphql was designed to solve.

(This is of course only a suggestion. So please ignore this issue if you already talked about this internally and decided to go with Rest).

**Comment by hpiwowar** [comment]
Hi!  Thanks for the suggestion!  We are going to go with REST for the api initially because it is what we are most familiar with and we are looking to launch this as quickly as possible, though we may consider additional access paths next year after the initial launch.  Thanks again!

**Comment by tobiasdiez** [comment]
Sure, this is very understandable!
